name: Validate Commits
description: Validate commits for conventional commit format
runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  github_token:
    description: 'GitHub Token'
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}
