name: hello-françois
on : [workflow_dispatch]

env:
  NAME: Francois
  ENTREPRISE: Semifir
  DAY: Lundi

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Dit Bonjour
        if: ${{env.NAME != 'Francois'}}
        run: echo "tu n'es pas françois non mais "
      - name: "coucou François"
        if: ${{env.NAME == 'Francois'}}
        run: echo "Salut $NAME ! tu Travailles ches $ENTREPRISE ? Alors bon $DAY à toi"