name: Validate Commits

on:
  push:
    branches:
      - 'features/test'
      - 'hotfix/test'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Validate Commits
        run: echo "Le message du commit n'est pas conventionnel" && exit 1 
